### PR TITLE
Error reporting

### LINKED ISSUE #16: Keep track of failures
I.e. keep a list of _files_ where the transformation failed or had some errors

### PR DESCRIPTION
**Pull request by nleanba**
Fixes #16 by adding a list of all transformed files with status (succesful, has_warnings, has_errors, failed).

This provides a minimal overview over the status of file transformations, actual errors and warnings are provided as comments in the ttl as before.

### CODE REVIEW

File: config/config.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 export const config = {
   title: "GG2RDF",
-  description: "The Plazi service to transform GoldenGate XML into Turtle RDF.",
```
Comment (retog) [inline config/config.ts:3]: Advertising this feature with so much detail in the project description seems exagerated

Comment (nleanba) [reply config/config.ts:3]: Slightly, but this seemed to me the simplest way to include a link to the status file on the index page.

The only place where that description shows up is on the index page, so using it to link to internal places that are not base-GHAct features seems appropriate

**Comment by retog** [comment]
The build fails with
```
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/linkedom@0.16.8/cached
  Lock file: /workspaces/gg2rdf/deno.lock
```
I don't see anything in this pull request that might cause the error. Does it work for you?

**Comment by nleanba** [comment]
> The build fails with
> ...

At which step of the build does it fail for you? For me it builds fine.

To me the error looks like it tried to download a dependency but got a file with the wrong hash, probably a network problem or outage on the other end. As it builds fine on my machine and on github actions, I think we can ignore this.
